version: "3.9"

services:

  app:
    build: .
    container_name: addlaw_app
    restart: always
    env_file:
      - .env
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - addlaw_net

  web:
    image: nginx:alpine
    container_name: addlaw_web
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - addlaw_net

  db:
    image: mysql:8.0
    container_name: addlaw_db
    restart: always
    environment:
      MYSQL_DATABASE: addlaw
      MYSQL_USER: addlaw
      MYSQL_PASSWORD: dea8Lemaipeeraew
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - addlaw_net

  queue:
    build: .
    container_name: addlaw_queue
    command: php artisan queue:work --tries=3 --timeout=90
    restart: always
    depends_on:
      - app
    networks:
      - addlaw_net

  scheduler:
    build: .
    container_name: addlaw_scheduler
    command: sh -c "while true; do php artisan schedule:run; sleep 60; done"
    restart: always
    depends_on:
      - app
    networks:
      - addlaw_net

networks:
  addlaw_net:

volumes:
  dbdata:
